### PR TITLE
Updated README.md

### LINKED ISSUE #7: [Doc] Enhance Readme documentation
Add the following to the readme
- Logo of community
- Greeting
- Contributor guideline
- commands available
- purpose
- socials
- contributors list

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
Fixes #7 

- [x] Added the logo of the community.
- [x] Added the name of the community.
- [x] Added the greeting.
- [x] Added the about section.
- [x] Added the link for contributing guidelines.
- [x] Added the link for code of conduct.
- [x] Added the supported commands.

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
Hey @jayesh-srivastava if you are still working on it then you can make it draft PR

**Comment by jayesh-srivastava** [comment]
Hey @kaiwalyakoparkar sure I'll make it draft PR. Can you please tell me why the check failed?

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava not your mistake. That's a greeting failure, leave it. Let me know if you need any help

**Comment by jayesh-srivastava** [comment]
Hey @kaiwalyakoparkar made it draft PR.

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava Awesome :boom: You can work on it on your pace just make sure the stable version has to be released on 1st August. So we need readme ready until then :smile:

**Comment by jayesh-srivastava** [comment]
@kaiwalyakoparkar yeah sure, will try my best to complete it before 1st August.

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava There are some conflicts, Please let me know if you need any help? add the current readme section under contributing guidelines

**Comment by jayesh-srivastava** [comment]
Hey @kaiwalyakoparkar , I have made the initial version of the README. Please have a look and approve. Will continue to add more features.

**Comment by jayesh-srivastava** [comment]
@kaiwalyakoparkar Do let me know if you want any changes. I am always available for help.

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava You will have to solve the conflicts. Pull the changes to your local. Solve the conflict and push it again.

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava nvm I resolved the conflict

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket: Thanks for your collaboration and contribution :smile:

**Pull request merged**
