### PR TITLE
Added Contributors List to README file.

### PR DESCRIPTION
**Pull request by VarunSAthreya**
## Fixes Issue

This PR fixes the following issues: #37 

#example

## Changes proposed
To add a dynamic list of current contributors in the README.md file.

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable)

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots 
Add all the screenshots which support your changes

Capture

### CODE REVIEW

**Comment by jayesh-srivastava** [comment]
Hey @VarunSAthreya , as I mentioned in the issue, the names/photos of the contributors should also direct any user to their github profiles. Please modify according to it. Let me know if you have any doubts : )

**Review by jayesh-srivastava — CHANGES_REQUESTED** [review]
No need for more complexity. It can be done the same way as the maintainer section.

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava Anything I could help with?

**Comment by jayesh-srivastava** [comment]
@kaiwalyakoparkar , No thanks, @VarunSAthreya was just needed to do some changes in his PR. If he isn't then I will myself.

**Comment by VarunSAthreya** [comment]
@jayesh-srivastava Then we should create a table manually, for the contributor's list. So I'll start working on that?

**Comment by jayesh-srivastava** [comment]
@VarunSAthreya Yeah that would be great. Please do.

**Comment by VarunSAthreya** [comment]
@jayesh-srivastava Is this okay?

Capture

**Comment by jayesh-srivastava** [comment]
@VarunSAthreya Lgtm. @kaiwalyakoparkar If you feel this is good, then please approve and merge it with the main, it looks good to me btw.

**Review by kaiwalyakoparkar — COMMENTED** [review]
Hey, @VarunSAthreya Just wanted to ask if this is dynamic. Like if a new contributor contributes then will he/she/they get added to list automatically or will have to add manually?

**Comment by kaiwalyakoparkar** [comment]
@VarunSAthreya I just found out that this issue was assigned to someone else Refer (#35) I guess there was some issue. Let me confirm with the assigned member else if they are working on it sadly I will have to discard PR. That's the reason I highly appreciate getting the issue assigned first. Hope you understand :smiley:

**Comment by VarunSAthreya** [comment]
> Hey, @VarunSAthreya Just wanted to ask if this is dynamic. Like if a new contributor contributes then will he/she/they get added to list automatically or will have to add manually?

The prior one was dynamic but for the present table version it should be added manually.

**Comment by kaiwalyakoparkar** [comment]
@VarunSAthreya Hope you read my other message as well. We will have to wait until I take follow up. And we need dynamic banner as we don't want to repeat same process over and over again.

**Comment by VarunSAthreya** [comment]
> @VarunSAthreya Hope you read my other message as well. We will have to wait until I take follow up. And we need dynamic banner as we don't want to repeat same process over and over again.

Yaa I have. Sure.

**Comment by kaiwalyakoparkar** [comment]
@VarunSAthreya I am really sorry to inform that I won't be able to accept this PR as the previous assignee has raised a PR. If you want you can help them here #45. Thank you for your contribution. You can still take up other issues :smile:

**Pull request closed without merging**
