### PR TITLE
Fixed typos and grammatical mistakes.

### PR DESCRIPTION
**Pull request by VarunSAthreya**
## Fixes Issue

This PR fixes the following issues: #39 

#example

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable)

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots 
Add all the screenshots which support your changes

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
Hey @VarunSAthreya I like you enthusiasm but you should ideally wait until the issue gets assigned to you :slightly_smiling_face:

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket: Thanks for Collaboration and contribution

**Comment by VarunSAthreya** [comment]
> Hey @VarunSAthreya I like you enthusiasm but you should ideally wait until the issue gets assigned to you 🙂

@kaiwalyakoparkar Sure I'll keep that in mind from next time.

**Comment by kaiwalyakoparkar** [comment]
Hey @VarunSAthreya Why did you close it? It was marked as ready to merge

**Comment by kaiwalyakoparkar** [comment]
@VarunSAthreya Please be patient. It will be deployed as planned :slightly_smiling_face:

**Comment by VarunSAthreya** [comment]
Sorry, @kaiwalyakoparkar by mistake I deleted the branch in my fork, so the PR got automatically closed.

**Comment by kaiwalyakoparkar** [comment]
@VarunSAthreya That's alright. I thought you closed it because I said that it's not assigned to you :sweat_smile:

**Pull request merged**
