### PR TITLE
fix: edTech word list increased(#14)

### PR DESCRIPTION
**Pull request by ItsMeIshan**
## Fixes Issue
(#14) edTech Word list increased 
This PR fixes the following issues :
- adds more flexibility to stop community members talk about other edTech startups

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable)

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagarised content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots 
Add all the screenshots which support your changes
Screenshot 2021-07-25 at 2 06 37 PM

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
Did you try checking and running all of them? Do all of them trigger?

**Comment by kaiwalyakoparkar** [comment]
Also remove gfg as it's an authentic source

**Comment by ItsMeIshan** [comment]
@kaiwalyakoparkar 
- I have removed gfg and all words related to it
- also I have tested the bot for all the words it's working absolutely fine!

**Review by kaiwalyakoparkar — COMMENTED** [review]
Thanks for the PR. I will confirm this list and will let you know the status about it.

**Comment by kaiwalyakoparkar** [comment]
Hey, @ItsMeIshan their's some conflict. Please solve it. If you need any help let me know :)

**Comment by ItsMeIshan** [comment]
> Hey, @ItsMeIshan their's some conflict. Please solve it. If you need any help let me know :)

hey, @kaiwalyakoparkar  let me check I guess I have to create ```env.sample```
also i need to ask a basic git doubt that as now the code has been updated so which command should i run ? to resume working on my forked code i guess ```git pull``` or i have to specify the remote as well ?

**Review by shuklaritvik06 — APPROVED** [review]
LGTM

**Comment by ItsMeIshan** [comment]
> LGTM

actually I need to create ```.env-sample``` again thats why the conflict is coming i am just confused in one small thing about git that which pull command should I write on my local machine to make it even with the upstream one

**Comment by ItsMeIshan** [comment]
hey, @kaiwalyakoparkar I think now there will be no conflicts. Do check if I am missing anything.

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket: Thanks for collaborating and contributing. Hope to see many more from you :smile:

**Pull request merged**
