### PR TITLE
[FIX] : Updated the Old Discord Link to Vanity URL 

### PR DESCRIPTION
**Pull request by vind3v17**
## Changes proposed

Here comes all the changes proposed through this PR : 

Replaced the old Discord URL with the New Vanity URL which we recently got.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by kaiwalyakoparkar — CHANGES_REQUESTED** [review]
Change all the vanity links to `https://discord.io/commclassroom` as these vanity URL will disappear if the server goes below the 30 boosts

**Comment by vind3v17** [comment]
yea makes sense. On it now!

**Comment by vind3v17** [comment]
hey @kaiwalyakoparkar. I Made the following changes you requested. Its good to go.

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket: Thanks for your collaboration and contribution

**Pull request merged**
