### PR TITLE
feat: alexjs

### LINKED ISSUE #84: [Bug]: Profane warning for 'Class'
### Describe the bug

The bot sends a profance word warrning for the word 'Class'. 

### To Reproduce

Type 'Class' with Community Monitor in your server.

### Expected Behavior

_No response_

### Screenshot/ Video

_No response_

### Desktop (please complete the following information)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by krishguptadev**
## Fixes Issue

This PR fixes the following issues:

fixes #84 

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots 
Add all the screenshots which support your changes

### CODE REVIEW

**Comment by SiddhantKhisty** [comment]
@krishguptadev  Can you please show a screenshot showing that the issue has been resolved?

**Comment by krishguptadev** [comment]
I have setup a completely different thing so screenshots won't work here

**Comment by kaiwalyakoparkar** [comment]
> I have setup a completely different thing so screenshots won't work here

Could you please explain this?

**Comment by krishguptadev** [comment]
> > I have setup a completely different thing so screenshots won't work here
> 
> Could you please explain this?

I setted up alexjs just like how it works in EddieBot

**Comment by krishguptadev** [comment]
But the embed is the same one as the old one... I could make it dynamic if you want

**Comment by kaiwalyakoparkar** [comment]
> > > I have setup a completely different thing so screenshots won't work here
> > 
> > 
> > Could you please explain this?
> 
> I setted up alexjs just like how it works in EddieBot

Okay, Could you please send the screen shot of bot working for offensive words?

**Comment by krishguptadev** [comment]
Ok 👍

**Comment by kaiwalyakoparkar** [comment]
Thanks, Please add it to the screenshots section of the description

**Comment by krishguptadev** [comment]
image
image
If you want I can set the profanity level as well so that he him and other words are not blocked

**Comment by SiddhantKhisty** [comment]
Please see what is the effect of typing the word 'class' and 'glass'

**Comment by krishguptadev** [comment]
image

**Comment by kaiwalyakoparkar** [comment]
@krishguptadev 
- [ ] Add screenshots in the description of the pr
- [ ] Remove the bot warnings for he, him, his, she, her, etc.

**Comment by SiddhantKhisty** [comment]
LGTM. Issue of Classroom monitor deleting the words seems to have been resolved

**Review by SiddhantKhisty — COMMENTED** [review]
LGTM. Fixes the issues of cursewords detection as well as including inclusivity in the community

**Comment by krishguptadev** [comment]
image
Also now it can be changed anytime using the config.json file

**Comment by krishguptadev** [comment]
> @krishguptadev
> 
> * [ ]  Add screenshots in the description of the pr
> * [ ]  Remove the bot warnings for he, him, his, she, her, etc.

Already added the SSs in the comments and removed the warning of he/him/she/her

**Comment by kaiwalyakoparkar** [comment]
> > @krishguptadev
> > 
> > * [ ]   Add screenshots in the description of the pr
> > * [ ]   Remove the bot warnings for he, him, his, she, her, etc.
> 
> Already added the SSs in the comments and removed the warning of he/him/she/her

It's alright now but it's a good practice to add in description else the person has to scroll to the end to find the screenshots

**Pull request merged**
