### PR TITLE
refactor: :sparkles: Refactored the codebase

### PR DESCRIPTION
**Pull request by Tan-Shadow**
## Changes proposed

Here comes all the changes proposed through this PR

- [x] Refactored the `index.js` to just execute the command with the name attribute in the exports instead of if else statements

- [x] Also added a “Please use a valid command” and “check `cm!help`” if the command is not available

- [x] Added a parameter Discord which should take the Discord object library so that we don’t have to require the Discord in each file 

- [x] Added **fs** to the `index.js` to read the commands/files from the Commands folder

- [x] Added checks in `client.on(“message”)` function to check for bot, dms, and if the command is starting with prefix or not

- [x] Changed the `dsa.js`,`source.js`, `version.js`, `hey.js`, `help.js`, `links.js` to export the name and description of the command to check that in `index.js` 

- [x] Changed the `translate.js` to use the latest **async/await** syntax instead of the old `.then()/.catch()` syntax, also changed checks for if the translation is is same as the input text and if the input args is empty  

- [x] Also changed the `meme.js` to use the async/await instead if .then and .catch, and made it to send a embed instead of simple text and image

- [ ] Deleted the `command` file which is not needed after the changes 

- [ ] Updated the version in the `config.json` 

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots 
Add all the screenshots which support your changes
Here are the screenshots...

Help command :-
https://tanshadow.is-inside.me/1OOa4wAy.png

Hey command :-
https://tanshadow.is-inside.me/gsmEDKwO.png

Version command :-
https://tanshadow.is-inside.me/pivOCiLm.png

Links command :-
https://tanshadow.is-inside.me/P2dXk8Rj.png

Translate command :-
( without args ) -> https://tanshadow.is-inside.me/OAHLvQcp.png
( with args ) -> https://tanshadow.is-inside.me/AkX6Bi00.png

 Meme command :- 
https://tanshadow.is-inside.me/9W1vBM3v.png

Source command :-
https://tanshadow.is-inside.me/W4q7h6N9.png

DSA command :-
https://tanshadow.is-inside.me/F76UlA7J.png

Commands don't work in dms :-
https://tanshadow.is-inside.me/WMPZVYgx.png

Restricted words :-
https://tanshadow.is-inside.me/OsxBbCc2.png
https://tanshadow.is-inside.me/MzVqPl5i.png

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
@Tan-Shadow Could you please add screenshots of working commands please

**Comment by Tan-Shadow** [comment]
I am sorry i will add them tomorrow as soon as i boot up

**Comment by Tan-Shadow** [comment]
@kaiwalyakoparkar screenshots addded 👍🏼

**Review by vishalda — APPROVED** [review]
LGTM!

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
