### PR TITLE
Change prefix to cm

### PR DESCRIPTION
**Pull request by Amrutha1101**
## Fixes Issue

This PR fixes the following issues : #16 

#example

## Changes proposed

Changed prefix to cm

## Check List (Check all the boxes which are applicable)

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagarised content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
Did you check the working of it locally? Is it working fine? If so could you please attach some screenshots so that I would verify :slightly_smiling_face:

**Comment by Amrutha1101** [comment]
Sorry can you help me how to check locally?

**Comment by kaiwalyakoparkar** [comment]
@Amrutha1101 no worries. Check the discussion on this repo. Folks are helping in setting up the project locally and testing it out.

**Comment by Amrutha1101** [comment]
Screenshot (181)

**Review by kaiwalyakoparkar — APPROVED** [review]
LGTM :rocket: Thanks for Collaboration and Contribution. Looking forward to see more contributions from you :)

**Comment by kaiwalyakoparkar** [comment]
@Amrutha1101 My pleasure. Good to see you coming forward and contributing. Hope to see many more from you :smile:

**Pull request merged**
